---
- name: Add repository EPEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present
    gpgcheck: true
    enabled: true

- name: MySQL 5.7 Community Server
  yum_repository:
    name: mysql57-community
    description: MySQL 5.7 Community Server
    baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
    enabled: true
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mysql

- name: Add Mysql GPG-Key
  copy:
    src: RPM-GPG-KEY-mysql
    dest: /etc/pki/rpm-gpg/
    owner: root
    group: root
    mode: 0644
