---
name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - molecule

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    container: geerlingguy/docker-centos8-ansible:testing

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: yamllint
        run: yamllint .
        shell: bash

      - name: ansiblie-lint
        run: ansible-lint lms-server.yml
        shell: bash

  test:
    needs: lint
    name: Molecule
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     distro:
    #       - centos8
    #       - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install molecule molecule-docker docker yamllint ansible-lint # ansible

      # - name: Install remote roles
      #   run: ansible-galaxy install dev-sec.os-hardening

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: "centos8"
          # MOLECULE_DISTRO: ${{ matrix.distro }}
